---
name: bump

on: [repository_dispatch]

jobs:
  bump:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Information
      run: |
        echo "Version update for ${{ github.event.client_payload.package_name }} -> ${{ github.event.client_payload.package_version }} requested"
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOOL_REPO_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Tag and push
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git am -3 < .github/workflows/0001-Disable-compile-tests-until-GradleRIO-released-.patch
        sed -i `s/wpilibRelease = \"/wpilibRelease = \"${{ github.event.client_payload.package_version }}\"/`src/main/java/robotbuilder/exporters/GenericExporter.java
        git commit -a -m "Bump export version to ${{ github.event.client_payload.package_version }}"
        git push origin
        git tag ${{ github.event.client_payload.package_version }}
        git push origin ${{ github.event.client_payload.package_version }}
        git revert HEAD~1
        git push origin
